image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:

  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
  # Запускаем автотесты
  # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
  # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
  - ./gradlew test --info -Dselenide.headless=true